### ISSUE TITLE
allow runtime specification of console output

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#111]
Stumpless will eventually be capable of writing some output to the console, for example once the CONS option is implemented (see #78). However, there is currently not a way to set the stream used for this, as there is for error streams for example. This could create difficulties for some use cases of the library, and at a minimum will make testing more difficult. This could be fixed by implementing two functions called `stumpless_get_console_stream` and `stumpless_set_console_stream` which operate as named.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block. You are also free to take a different approach if you feel it is better - this is merely meant as a starting point.

First, check out the documentation and definitions of `stumpless_get_error_stream` and `stumpless_set_error_stream` in `include/stumpless/error.h` and `src/error.c`, respectively. These function very similarly to what you will be implementing and serve as a great template for getting started. Pay special attention to the variables they work with and how they are initialized. These functions use atomic variables to maintain thread safety while they operate.

Next, you need to add these two functions and their supporting variables. The best place for them currently is the target module (`include/stumpless/target.h` and `src/target.c`), which will need to write to the specified stream in the event of a failure once #78  is implemented. As you add your functions, also be sure to add them to the Windows definition file (`src/windows/stumpless.def`) and the header check tool in `tools/check_headers/stumpless.yml`. The [Adding New Functions](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) section of the development guide talks about this in more detail.

Once you have these added and documented, you just need to add some tests to ensure that they are covered. Your tests will be fairly simple, consisting of the following checks:
  1. Make sure that the default console is `stdout`
  1. Make sure that the stream is changed after calling set on it.
  1. `NULL` is a valid argument to set the console. This should result in any output meant for the stream simply getting dropped, effectively removing the stream.

These tests should be added to the target test suite in `test/function/target.cpp`, which has a large number of other tests that you can use for comparison. There are some stream setting tests for the existing error stream get/set functionality in `test/function/error.cpp` that you can also draw inspiration from.

**Comment by Jk-bit** [comment]
I would like to work on this and then continue with the CONS options

**Comment by goatshriek** [comment]
Sounds good!
