### ISSUE TITLE
length checking of the msgid

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#113]
The syslog RFC ([RFC 5424](https://tools.ietf.org/html/rfc5424)) specifies a given length for many fields of a log message, including the msgid. Checking the length of supplied msgid arguments will not only help users stay compliant with the standard, but will also allow for efficiencies in the implementation by eventually allowing for the use of fixed-length buffers instead of memory allocated on the heap.

As specified in the RFC, msgid parameters should be checked for their length and rejected if they are more than the allowed length (32 characters). Note that this length does not include the terminating NULL character from the C string representation.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block. You are also free to take a different approach if you feel it is better - this is merely meant as a starting point.

There are a number of functions that allow a msgid to be supplied - the constructor for entries, the set feature for the msgid of entries, and the default msgid setting for targets, to list a few. Since this check will need to take place in several places, you will be best served by implementing it in a single function and then calling it wherever required.

Declare your new function (something like `validate_msgid_length`) in `include/private/validate.h`, and define it in `src/validate.c`. You will need to create the latter of these files - don't forget to add it to the source file list `STUMPLESS_SOURCES` in `CMakeLists.txt`. After it has been defined, add calls to it wherever a msgid is passed as a parameter in the library, which are the following functions:
 * `vstumpless_new_entry` (in `src/entry.c`)
 * `stumpless_set_entry_msgid` (in `src/entry.c`)
 * `stumpless_set_target_default_msgid` (in `src/target.c`)

An error already exists that should be used for invalid message ids: `STUMPLESS_ARGUMENT_TOO_BIG`. Raise this error in your validation function if a msgid that is too long is detected, using the `raise_argument_too_big` function from `src/error.c`.

Don't forget to add tests for your new functionality! These should go alongside the tests for the functions that have msgids - check `test/function/target.cpp` and `test/function/entry.cpp` for existing tests for these functions, and add new tests that make sure that msgids that are too long are rejected.

**Comment by LambdaApproach** [comment]
Hi there, I'd like to take a crack at this if nobody else is currently working on it.

**Comment by goatshriek** [comment]
Sounds good! I will go ahead and assign it to you. Feel free to reach out if you need any clarification or have any other questions.

**Comment by LambdaApproach** [comment]
Looks like I need to create a new error message and error message code type for this since I can't find any of them that really fit the description of this particular kind of error. 

Closest I could find is "L10N_MESSAGE_SIZE_ERROR_CODE_TYPE" but that's an error code for the overall size of the message and I can't find an accompanying error message for it.

What do you think?

Edit: To clarify, what I currently have is a simple if statement that checks for the msgid length with the help of the `strlen` function, and within that if statement an error is raised if the length is beyond 32 characters. It's just that I don't think I'm using the `raise_argument_too_big ` function arguments properly, hence why I'm asking about the error message and error code to use for that function.

**Comment by goatshriek** [comment]
That is a good point - it would be best to create a new message and code type as you suggest so that the error is clear to the user. Perhaps something along the lines of STRING_TOO_LONG with the error code being the length of the offending string? It should be re-usable for length checks of other fields in the future.

You may have already found [this document](https://github.com/goatshriek/stumpless/blob/latest/docs/localization.md#adding-new-strings), but it includes information on adding new localization strings. Be sure to add the placeholders for the other four (es-es, fr-fr, de-de, and sv-se) as well.
