### ISSUE TITLE
implement spanish (es-ES) localization

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#120]
Localization has been added to the library, and Spanish (es-ES) has since been added with stub values. However, these messages are not useful and need to be replaced with actual Spanish to be of any use.

This will be straightforward for someone that speaks the language, even if you have very little knowledge of C. You will simply need to update the strings in `include/private/config/locale/es-es.h` with Spanish strings (in UTF-8 encoding). If you want to see what the English message is, check the corresponding values in `include/private/config/locale/en-us.h`.

**Comment by ulisesten** [comment]
Does this need help yet?

**Comment by goatshriek** [comment]
It is all yours if you would like to work it!

**Comment by ulisesten** [comment]
ok, let's do it
