### ISSUE TITLE
length checking of the app-name

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#129]
The syslog RFC ([RFC 5424](https://tools.ietf.org/html/rfc5424)) specifies a maximum length for many fields of a log message, including the app-name field. Checking the length of supplied app-name arguments will not only help users stay compliant with the standard, but will also allow for efficiencies in the implementation by eventually allowing for the use of fixed-length buffers instead of memory allocated from the heap.

As specified in the RFC, app-name parameters should be checked for their length and rejected if they are more than the allowed length (48 characters). Note that this length does not include the terminating NULL character from the C string representation.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block. You are also free to take a different approach if you feel it is better - this is merely meant as a starting point.

There are a number of functions that allow an app-name to be supplied - the constructor for entries, the set feature for the app-name of entries, and the default app-name setting for targets, to list a few. Since this check will need to take place in several places, you will be best served by implementing it in a single function and then calling it wherever required.

Declare your new function (something like `validate_app_name_length`) in `include/private/validate.h`, and define it in `src/validate.c`. A similar validation function has already been created for msgids - use it as a reference as needed. After your new function has been defined, add calls to it wherever an app-name is passed as a parameter in the library, which are the following functions:
 * `vstumpless_new_entry` (in `src/entry.c`)
 * `stumpless_set_entry_app_name` (in `src/entry.c`)
 * `stumpless_set_target_default_app_name` (in `src/target.c`)

Update the documentation for each of these functions to specify that the app name length is restricted to be 48 characters or less. The relevant documentation is in a doxygen comment format in the include files corresponding to the source files (`include/stumpless/entry.h` and `include/stumpless/target.h`). Add the note about this to the `@param` descriptions of the app-name parameters.

An error already exists that should be used for invalid app-names: `STUMPLESS_ARGUMENT_TOO_BIG`. Raise this error in your validation function if an app-name that is too long is detected, using the `raise_argument_too_big` function from `src/error.c`. Again, the existing validation function for msgids is a good reference point to look at.

Don't forget to add tests for your new functionality! These should go alongside the tests for the functions that have app-names - check `test/function/target.cpp` and `test/function/entry.cpp` for existing tests for these functions, and add new tests that make sure that app-names that are too long are rejected.

**Comment by hoomaac** [comment]
I'm on it.
