### ISSUE TITLE
format checking of app-name

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#130]
The syslog RFC ([RFC 5424](https://tools.ietf.org/html/rfc5424)) specifies that a number of fields only include printable ASCII characters (decimal values 33 to 126 inclusive), including the app-name. Checking the characters of supplied app-name arguments will not only help users stay compliant with the standard, but will also provide a point of mitigation for encoding bugs and vulnerabilities.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

There are a number of functions that allow an app-name to be supplied - the constructor for entries, the set feature for the app-name of entries, and the default app-name setting for targets. Since this check will need to take place in several places, you will be best served by calling a single function wherever required.

But good news: a function that does this already exists! It is in `src/validate.c` and is named `validate_msgid_format`. You just need to do some refactoring of this function to make it more generalized to support app-names (and other fields in the future). This amounts to renaming the function to something more general (perhaps `validate_printable_ascii`?) and changing invocations of it to this new name. An easy approach to take here is to rename the definition and declaration, and then follow the resulting compile errors to find the invocations. Or do a `grep`! Or some other find/replace method, it is up to you.

After this refactoring, add calls to the function wherever an app-name is passed as a parameter in the library, which are the following functions:
 * `vstumpless_new_entry` (in `src/entry.c`)
 * `stumpless_set_entry_app_name` (in `src/entry.c`)
 * `stumpless_set_target_default_app_name` (in `src/target.c`)

Update the documentation for each of these functions to specify that the app name is restricted to specific characters. The relevant documentation is in a doxygen comment format in the include files corresponding to the source files (`include/stumpless/entry.h` and `include/stumpless/target.h`). Add the note about this to the `@param` descriptions of the app-name parameters.

Don't forget to add tests for your new functionality! These should go alongside the tests for the functions that have app-names - check `test/function/target.cpp` and `test/function/entry.cpp` for existing tests for these functions, and add new tests that make sure that app-names with invalid characters are rejected.

**Comment by CuckooEXE** [comment]
Gave it my best shot with https://github.com/goatshriek/stumpless/pull/172. Take a look and let me know what you think, and if it needs any changes. Thanks!

**Comment by goatshriek** [comment]
Thanks so much for putting this together! I've left a review with some requested changes, but you're definitely on the right track!
