### ISSUE TITLE
implement element to string function

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#146]
It is often useful to be able to obtain a string representation of a given value either for user interface hints, troubleshooting, or operations like value comparison. Such a function is currently implemented for some stumpless data types (like the version struct) but not for others, including the element struct.

Note that this function is _not_ intended for use in the formatting of a log message as this output may be subtly different, for example when escape codes are needed. Rather, it is meant to give an as-is represenation of the element itself (name and all params).

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block. You are also free to take a different approach if you feel it is better - this is merely meant as a starting point.

Before you start, take a peek at bb30c61b82be4fa031a719c8457b562981fef8cf which implements a similar functionality for params. You will need to use the function implemented here, and the basics of this change will also apply to this one as well.

First, read [this specific section](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) of the development guide devoted to adding new functions. It provides an outline of the work you will need to do beyond the implementation and testing of the function.

Next, add a declaration for your function in the `include/stumpless/element.h` header file. Name the function `stumpless_element_to_string` and document its behavior in the same doxygen format as the others in the same header. Make sure to cover the following points:
 * the general format of the output (suggested: `<name>` (with no params), `<name>:[param_1_to_string,param_2_to_string,etc.]` with params)
 * the supplied argument should be a `const` pointer
 * explicitly state that the result must be freed when it is no longer needed

Now you are ready to add the matching implementation for the function in `src/element.c`. Use the code for existing functions in this file as examples. You will also need to use `stumpless_param_to_string` to get the string representation of any params in the element. Be sure that there is no memory leak in your result, and try to avoid expensive operations like `sprintf` - you should be able to do this with `memcpy` calls and assignments, and perhaps `strlen` calls. You may consider refactoring some common portions of `stumpless_param_to_string` into separate private functions that can be used in both places for efficiency, but don't worry if you don't want to go this far - it can be turned into a follow-on first issue for others to tackle.

Finally, be sure to add tests for the new function. These should go in `test/function/element.cpp` and should achieve full coverage, including for memory allocation failure and NULL argument cases. Again, there are already similar test cases for other functions in this file that you can look at to get a general idea of how the tests should be structured.

**Comment by northernSage** [comment]
Awesome documentation! I'll chip in and tackle this one as time allows 👍🏻

**Comment by goatshriek** [comment]
Great! I'll go ahead and reserve it as yours.
