### ISSUE TITLE
length checking of param names

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#147]
The syslog RFC ([RFC 5424](https://tools.ietf.org/html/rfc5424)) specifies a maximum length for many fields of a log message, including param names. Checking the length of supplied param name arguments will not only help users stay compliant with the standard, but will also allow for efficiencies in the implementation by eventually allowing for the use of fixed-length buffers instead of memory allocated from the heap.

As specified in the RFC, param names should be checked for their length and rejected if they are more than the allowed length (32 characters). Note that this length does not include the terminating NULL character from the C string representation.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block. You are also free to take a different approach if you feel it is better - this is merely meant as a starting point.

There are a number of functions that allow parameter name to be supplied - the constructor for params, and the functions that allow new params to be added to elements and entries directly. Since this check will need to take place in several places, you will be best served by implementing it in a single function and then calling it wherever required.

Declare your new function (something like `validate_param_name_length`) in `include/private/validate.h`, and define it in `src/validate.c`. Similar validation functions have already been created for msgids and app names - use them as a reference as needed. After your new function has been defined, add calls to it wherever a param name is passed as a parameter in the library, which are the following functions:
 * `stumpless_new_param` (in `src/param.c`)
 * `stumpless_set_param_name` (also in `src/param.c`)
 * `stumpless_add_new_param` (in `src/element.c`)
 * `stumpless_add_new_param_to_entry` (in `src/entry.c`)

Note that you don't need to validate names passed to search functions like `stumpless_get_param_by_name` as the search will simply fail for non-compliant names.

Update the documentation for each of these functions to specify that the param name length is restricted to be 32 characters or less. The relevant documentation is in a doxygen comment format in the include files corresponding to the source files (`include/stumpless/param.h`, `include/stumpless/element.h`, and `include/stumpless/entry.h`). Add the note about this to the `@param` descriptions of the param name parameters.

An error already exists that should be used for invalid  param names: `STUMPLESS_ARGUMENT_TOO_BIG`. Raise this error in your validation function if a param name that is too long is detected, using the `raise_argument_too_big` function from `src/error.c`. Again, the existing validation functions for msgids and app names are good references to look at.

Don't forget to add tests for your new functionality! These should go alongside the tests for the functions that have param names - check `test/function/param.cpp`, `test/function/element.cpp`, and `test/function/entry.cpp` for existing tests for these functions, and add new tests that make sure that param names that are too long are rejected.

**Comment by giannalammer** [comment]
Hello. I would like to help work on this issue. I have a strong knowledge of programming in c.

**Comment by goatshriek** [comment]
Hello Gianna, thanks for reaching out! I will assign this to you so that others can see you are working it. Please feel free to reach out with any questions!

**Comment by goatshriek** [comment]
@giannalammer just checking in to see if you are still planning to work this? No worries if not, I just want to open it up for others if that's the case.

**Comment by anindyasen** [comment]
Planning to work on this one once done with issue 187.

**Comment by anindyasen** [comment]
What will be the max param length?

**Comment by anindyasen** [comment]
FIx for this issue is not required?

**Comment by goatshriek** [comment]
@anindyasen [Project policy](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md#you-still-there) gives stale issue assignees a month to respond to a request for an update, and we will honor that policy here.

However, I do understand that waiting that long would put you outside of the hacktoberfest timeline. Give me a bit and I will open a new issue for the length checking of element names, which will be largely identical to this one, for you to work on in place of this one.

**Comment by anindyasen** [comment]
So in that new issue should I fix for both param and element or only element?

**Comment by goatshriek** [comment]
I've created #189 to cover this - if you drop a comment on it I can assign it to you. It's only for element names: max length of 32 characters.

@giannalammer will have a month to respond to the request for an update before this param name length checking issue is released for others to work.

**Comment by goatshriek** [comment]
This issue is now re-open for anyone that would like to try it.

**Comment by igorkole** [comment]
Hi @goatshriek, I'd like to contribute to this issue.

**Comment by goatshriek** [comment]
Sounds good! I will assign it to you so others know it is in work.
