### ISSUE TITLE
check target type in close functions

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#162]
There is a specific function for closing each type of target, but it does not check the type of the target before closing. If passed the wrong type of target, this could lead to memory corruption and/or crashing.

While this would be a user error, a check for the target type would reduce the chance of this becoming a problem. A future build option to remove error checks if needed would allow the performance penalty to be removed if users can guarantee they won't violate this.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block. You are also free to take a different approach if you feel it is better - this is merely meant as a starting point.

First, take a look at the `raise_target_incompatible` function in `include/private/error.h`. You will use this function to raise an error when the wrong target type is detected.

You need a string to pass to the error raising function as the error message. Since there isn't an appropriate one existing, you will need to add a new one to the locales. Check out the [documentation on localization](https://github.com/goatshriek/stumpless/blob/latest/docs/localization.md#adding-new-strings) for instructions on how to do this.

Implementing the actual checks is straightforward. For each close function (of the form `stumpless_close_xxx_target`) in the target modules (in the `src/target/` directory), add a check on the target's type and raise an error (and return of course) if it is not the expected type.

Finally, add tests for each modification to make sure that trying to close the wrong target type is caught. For each target type, look at the existing test suite (these are in the `test/function/target/` directory) and add a test for the close test with a different target type. A good starting place is the test that passes `NULL` into the function and checks for an error - copy this test and modify it to test for the new scenario.

**Comment by ShobhitSamuelSingh** [comment]
Hi, I would like to work on this issue.

**Comment by goatshriek** [comment]
Sounds good! I have assigned you so that it's clear to folks that someone is working on this.

**Comment by ShobhitSamuelSingh** [comment]
Thank you for assigning me the issue. Please check if the changes made are correct and I couldn't add test cases because I didn't know how to, please help me with that too.

**Comment by goatshriek** [comment]
Sure thing, I provided comments and more information in #163 for you to take a look at.

**Comment by goatshriek** [comment]
This issue is re-open for anyone that would like to work on it. The pull request referenced above has initial work done by @ShobhitSamuelSingh which is a good starting point if you would prefer not to start from scratch.
