### ISSUE TITLE
format checking of param names

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#177]
The syslog RFC ([RFC 5424](https://tools.ietf.org/html/rfc5424)) specifies that a number of fields only include printable ASCII characters (decimal values 33 to 126 inclusive), including structured data identifiers such as param names. In addition to being limited to printable ASCII, identifiers have even more restricted characters that are not allowed. Checking the characters of supplied identifiers will not only help users stay compliant with the standard, but will also provide a point of mitigation for encoding bugs and vulnerabilities.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

There are a number of functions that allow a param name to be supplied: the constructor for params, accessor and mutator functions for entries and elements. Since this check will need to take place in several places, you will be best served by calling a single function wherever required.

A validation function already exists to check that a string only contains printable ASCII characters: `validate_printable_ascii` in `src/validate.c`. You will need to define a new function in the same file for structured data identifiers, adding the restriction that the string also not contain these characters and raising an encoding error if it does:
 * an equal sign `=`, decimal value 61
 * a closing brace `]`, decimal value 93
 * a double-quote character `"`, decimal value 34

After this addition, add calls to your new function in functions where a param name is passed as a parameter in the library, which are listed below. For functions where the parameter is used for a search, be sure to check the name _before_ acquiring any locks to avoid deadlock and improve performance.
 * `stumpless_new_param` (in `src/param.c`) This function is used by all others that create a new param, and so explicit checks are not needed in those.
 * `stumpless_set_param_name` (in `src/param.c`) This function is used by all others that modify a param name, and so explicit checks are not needed in those.
 * `stumpless_element_has_param` (in `src/element.c`)
 * `stumpless_get_param_by_name` (in `src/element.c`)
 * `stumpless_get_param_index` (in `src/element.c`)
 * `stumpless_get_param_name_count` (in `src/element.c`)
 * `stumpless_get_param_value_by_name` (in `src/element.c`)
 * `stumpless_get_entry_param_by_name` (in `src/entry.c`)
 * `stumpless_get_entry_param_value_by_name` (in `src/entry.c`)

Update the documentation for the first two of these functions (creation and modification) to specify that the param name is restricted to specific characters. The relevant documentation is in a doxygen comment format in the `include/stumpless/param.h` header file. Add the note about this to the `@param` descriptions of the param name parameters.

Don't forget to add tests for your new functionality! These should go alongside the tests for the functions that have param names. Find the existing tests for these functions as starting points, and add new tests that make sure that param names with printable but invalid characters are rejected.

**Comment by northernSage** [comment]
I'll give this one a go 👍🏻

**Comment by goatshriek** [comment]
Awesome!
