### ISSUE TITLE
implement format checking of element names

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#187]
The syslog RFC ([RFC 5424](https://tools.ietf.org/html/rfc5424)) specifies that a number of fields only include printable ASCII characters (decimal values 33 to 126 inclusive), including structured data identifiers such as element names. In addition to being limited to printable ASCII, identifiers have other restricted characters that are also not allowed. Checking the characters of identifiers will not only help users stay compliant with the standard, but will also provide a point of mitigation for encoding bugs and vulnerabilities.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

A similar issue for param names has already been tackled, and is a great place to review if you want some more preparation material. Check out the excellent work by Gabriel Fioravante in #177 and #184 for inspiration.

There are a number of functions that allow a element name to be supplied: the constructor for elements, accessor and mutator functions for entries and elements. Since this check will need to take place in several places, you will be best served by calling a single function wherever required.

A validation function already exists to check that a string contains only allowed characters: `validate_param_name` in `src/validate.c`. You will need to either copy this function and change the copy for element names or refactor the current one (via rename) to support both.

After this change, add calls to your new function wherever an element name is passed as a parameter in the library, which are listed below. For functions where the element name is used for a search, be sure to check the name _before_ acquiring any locks to avoid deadlock and improve performance.
 * `stumpless_new_element` (in `src/element.c`) This function is used by all others that create a new element, and so explicit checks are not needed in those.
 * `stumpless_set_element_name` (in `src/element.c`) This function is used by all others that modify an element name, and so explicit checks are not needed in those.
 * `stumpless_entry_has_element` (in `src/entry.c`)
 * `stumpless_get_element_by_name` (in `src/entry.c`)
 * `stumpless_get_element_index` (in `src/entry.c`)
 * `stumpless_get_entry_param_by_name` (in `src/entry.c`)
 * `stumpless_get_entry_param_value_by_name` (in `src/entry.c`)

Update the documentation for the first two of these functions (creation and modification) to specify that the element name is restricted to specific characters. The relevant documentation is in a doxygen comment format in the `include/stumpless/element.h` header file. Add the note about this to the `@param` descriptions of the element name parameters.

Don't forget to add tests for your new functionality! These should go alongside the tests for the functions that have element names. Find the existing tests for these functions as starting points, and add new tests that make sure that element names with printable but invalid characters are rejected.

**Comment by anindyasen** [comment]
I am participating in hacktoberfest. Can I  try to fix this issue as a part of that.
Also one query on the issue, for element verification, will the restrictions be same as param validation done in function validate_param_name? 

Thank you

**Comment by goatshriek** [comment]
Sure thing! I will assign it to you so others can quickly see it is in work.

**Comment by anindyasen** [comment]
Also one query on the issue, for element verification, will the restrictions be same as param validation done in function validate_param_name?

**Comment by goatshriek** [comment]
Yes, the validation performed is the same. You can either duplicate the function or rename it for re-use, up to you!

**Comment by anindyasen** [comment]
Thanks @goatshriek for the info. Few more queries,
1. How test function are working? How to write the test I understood, but how to run the test functions to check my code change?
2. Also can same test function be used to validate both param and element name. For eg, 
 TEST_F( ElementTest, GetParamInvalidName ) we can also pass different element name to test. Is that allowed or I need to create a new test function.

Thank you,

**Comment by goatshriek** [comment]
The easiest way to run the test suite is to use the `check` target, which will build and run all tests. So for example if you are in a make environment, `make check`. I need to add better docs on the unit test suite, I will try to do that in the next 7 days or so.

It would be best to create a new test function (that is, a new `TEST_F` call) so that tests are independent. This makes for faster troubleshooting, since a failure immediately indicates which call is failing based on the test itself.

**Comment by goatshriek** [comment]
I've started a draft of some more detailed test documentation in the `test-docs` branch - have a look at the [test.md](https://github.com/goatshriek/stumpless/blob/test-docs/docs/test.md) doc there to see if it answers your questions. Any feedback is welcome!

**Comment by anindyasen** [comment]
The test document looks good.
