### ISSUE TITLE
length checking of element names

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#189]
The syslog RFC ([RFC 5424](https://tools.ietf.org/html/rfc5424)) specifies a maximum length for many fields of a log message, including element names. Checking the length of supplied element name arguments will not only help users stay compliant with the standard, but will also allow for efficiencies in the implementation by eventually allowing for the use of fixed-length buffers instead of memory allocated from the heap.

As specified in the RFC, element names should be checked for their length and rejected if they are more than the allowed length (32 characters). Note that this length does not include the terminating NULL character from the C string representation.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block. You are also free to take a different approach if you feel it is better - this is merely meant as a starting point.

There are a number of functions that allow element names to be supplied - the constructor for elements, and the functions that allow new elements to be added to entries directly. Since this check will need to take place in several places, you will be best served by implementing it in a single function and then calling it wherever required.

Declare your new function (something like `validate_element_name_length`) in `include/private/validate.h`, and define it in `src/validate.c`. Similar validation functions have already been created for msgids and app names - use them as a reference as needed. After your new function has been defined, add calls to it wherever a element name is passed as a parameter in the library, which are the following functions:
 * `stumpless_new_element` (in `src/element.c`)
 * `stumpless_set_element_name` (also in `src/element.c`)
 * `stumpless_add_new_element` (in `src/entry.c`)
 * `stumpless_add_new_param_to_entry` (in `src/entry.c`)

Note that you don't need to validate names passed to search functions like `stumpless_get_element_by_name` as the search will simply fail for non-compliant names.

Update the documentation for each of these functions to specify that the element name length is restricted to be 32 characters or less. The relevant documentation is in a doxygen comment format in the include files corresponding to the source files (`include/stumpless/element.h` and `include/stumpless/entry.h`). Add the note about this to the `@param` descriptions of the element name parameters.

An error already exists that should be used for invalid element names: `STUMPLESS_ARGUMENT_TOO_BIG`. Raise this error in your validation function if an element name that is too long is detected, using the `raise_argument_too_big` function from `src/error.c`. Again, the existing validation functions for msgids and app names are good references to look at.

Don't forget to add tests for your new functionality! These should go alongside the tests for the functions that have element names - check `test/function/element.cpp` and `test/function/entry.cpp` for existing tests for these functions, and add new tests that make sure that element names that are too long are rejected.

**Comment by anindyasen** [comment]
Will start working on this one. Max length is 32.

**Comment by anindyasen** [comment]
```stumpless_add_new_element``` and ```stumpless_add_new_param_to_entry``` is calling stumpless_new_element  where check is there. Is it still needed in this functions?

**Comment by goatshriek** [comment]
As long as the tests still show these returning an accurate error message, you can probably rely on the check of the lower function if you would like.

However, note that this is less performant in multithreaded code as that check won't happen until after a lock is acquired. Checking the name and returning an error before locking would be faster (and less prone to thread safety mistakes).
