### ISSUE TITLE
refactor tests for invalid format items

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#193]
Tests for names and other elements with formatting errors use much of the same code, and could be made more compact by refactoring the common code into helper test functions. Some documentation on creating and using test helpers can be found in [test/README.md](https://github.com/goatshriek/stumpless/blob/latest/test/README.md) and [docs/test.md](https://github.com/goatshriek/stumpless/blob/latest/docs/test.md)

See the discussion of #184 for the context behind this request.

**Comment by Marecek460** [comment]
Hello. I would like to help work on this issue.

**Comment by goatshriek** [comment]
Absolutely! I have assigned the issue to you to mark it as in work. This issue is admittedly a little vague, so please reach out if you have any questions or need clarification.

**Comment by goatshriek** [comment]
Hello @Marecek460, just checking to see if you still intend to work on this? No worries if not, just want to see if this should be released for others.

**Comment by goatshriek** [comment]
This item is open for others to tackle once more.

**Comment by goatshriek** [comment]
Resolved by #474.
