### ISSUE TITLE
implement polish (pl-PL) localization

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#199]
There is a detailed guide on how to go about adding a new language in the [localization documentation](https://github.com/goatshriek/stumpless/blob/latest/docs/localization.md).

If you'd like a concrete example of such a change, check out commit c944d31b33934aa9a55c4858441affff8a9db813, which shows how to update the various build and header files outlined in the documentation.

**Comment by Marecek460** [comment]
Can you please assign me to issue. Thank you.

**Comment by goatshriek** [comment]
Hello @Marecek460, no pressure, but I just want to check in to see if you're still planning to work this? No worries if not, I can unassign you so that anyone else that comes along knows that this is free to work on.

**Comment by goatshriek** [comment]
in work via #217
