### ISSUE TITLE
unsafe multithreaded writes in PERROR option

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#207]
As noted by @Jk-bit in the [community Gitter](https://gitter.im/stumpless/community), the output generated by the `STUMPLESS_OPTION_PERROR` option on targets writes to the error stream without any sort of multithreading protection, which could potentionally lead to issues. These writes should be protected by the `error_stream_free` mutex in `src/error.c` that is used for `stumpless_perror` already.

**Comment by Jk-bit** [comment]
Pull request #208
