### ISSUE TITLE
string conversion function for facility levels

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#216]
It is often useful to be able to obtain a string representation of a given value for user interface hints, troubleshooting, or operations like value comparison. Such a function is currently implemented for some stumpless data types (like the severity enumeration) but not for others, including the facility enumeration.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, check out a8b701da6d2f32c4cc3c29687e1a7769490645cb and the implementation of `stumpless_get_severity_string` in `include/stumpless/severity.h` and `src/severity.c`. The implementation and documentation of this function are very similar to what you should do for yours. Pay particular attention to the `severity_enum_to_string` array, which provides a mapping from the enumeration value to the string itself.

Next, read [this specific section](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) of the development guide devoted to adding new functions. It provides an outline of the work you will need to do beyond the implementation and testing of the function.

Next, add a declaration for your function in the `include/stumpless/facility.h` header file. Name the function `stumpless_get_facility_string` and document its behavior in the same doxygen format as the others in the header. Make sure to cover the following points:
 * the format of the output (string literal of the symbol, perhaps give an example as well)
 * explicitly state that the result is a string literal that shouldn't be modified or freed by the caller

Now you are ready to add the matching implementation for the function in `src/facility.c`. Use the code for `stumpless_get_severity_string` as an example.

Finally, you'll need to add tests for the new function. These should go in a new test suite, `test/function/facility.cpp`, and should achieve full coverage, including for a facility that doesn't exist. Once again, the easiest path to success here will be looking at what was done in a8b701da6d2f32c4cc3c29687e1a7769490645cb and doing something very similar. There is some documentation on adding a new test suite [here](https://github.com/goatshriek/stumpless/blob/latest/docs/test.md#adding-tests-to-the-build), and the other test suites can serve as an example of what these should look like. A good test suite to copy and modify, of course, is the `test/function/severity.cpp` file.

**Comment by ivandev-81** [comment]
hello , Is this issue still open? 
I want collaborate

**Comment by goatshriek** [comment]
Absolutely! I will assign it to you so that it is clear you are working on it.

**Comment by ivandev-81** [comment]
> Absolutely! I will assign it to you so that it is clear you are working on it.

sure, I'll work on that

**Comment by ivandev-81** [comment]
Hello people, I'm so sorry, I was checking carefully the project and the tasks, and due to my school/work issues I can't work on the issue and I don't feel identified with the project, I'm focused on another kind  of technology right now.

**Comment by goatshriek** [comment]
No worries at all, thanks for checking in with a status, it's much appreciated.

**Comment by asinum** [comment]
Hello, it seems that no one is working on it right now and even if I'm not really experienced, it looks like a good point to start a participation if you're okay with that.

**Comment by goatshriek** [comment]
For sure! I will assign it to you so that it is reserved for you. Feel free to check in with any questions or if you'd like to leave it for someone else!
