### ISSUE TITLE
implement greek (el-GR) localization

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#240]
There is a detailed guide on how to go about adding a new language in the [localization documentation](https://github.com/goatshriek/stumpless/blob/latest/docs/localization.md).

If you'd like a concrete example of such a change, check out commit 5529e077eb75c6e79d5634e9d7fc708828b78f89, which shows how to update the various build and header files outlined in the documentation.

**Comment by SwoleDuck** [comment]
Perfect, i assume i'll have it ready in the next 2-3 days (based on how much free time i'll have).

**Comment by SwoleDuck** [comment]
Just finished with the translation and made a pull request, i'll be awaiting further news

**Comment by goatshriek** [comment]
Looks great, thank you so much for putting this together!
