### ISSUE TITLE
network target protocol accessor functions

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#244]
Network targets are created with specific network and transport protocols, for example IPv6 (network) over TCP (transport). However, there is not currently a public-facing function to retrieve this information about a target after it has been created. Your task is to add these new functions.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read [this](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) section of the development documentation on adding new functions. Once you understand how this process works, start defining the two new functions. They should have the following signatures:

```c
STUMPLESS_PUBLIC_FUNCTION
enum stumpless_network_protocol
stumpless_get_network_protocol( const struct stumpless_target *target );

STUMPLESS_PUBLIC_FUNCTION
enum stumpless_transport_protocol
stumpless_get_transport_protocol( const struct stumpless_target *target );
```

Your new functions will be declared in `include/stumpless/target/network.h` and defined in `src/target/network.c`. Be sure that you handle the possibility of a non-network target being provided (other functions in the `network.c` module show how to handle this).

Finally, once you've implemented the new functions, be sure you add tests for them! These should go in `test/function/target/network.cpp` and exercise all possibilities (normal behavior, NULL argument, incompatible target, anything else you can think of).

**Comment by Harry-Ramsey** [comment]
Hello, could I be assigned this issue? Seems quite interesting and a nice starting point to contributing to the project.

**Comment by goatshriek** [comment]
Absolutely! I'll assign it to you to reflect that you're working on it.
