### ISSUE TITLE
add target type to string function

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#246]
Several of the enumerations in stumpless are defined using a set of preprocessor functions and definitions, so that string conversion functions can be cleanly generated without repeating code. The target type enumeration is currently not done this way, meaning that a clean string conversion for target types is not easy to write. Your task is to refactor the target type enumeration to use this same scheme, and implement the to string function for the enumeration using this.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read [this](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) section of the development documentation on adding new functions. Once you understand how this process works, you'll be ready to define the new function.

Next, have a look at `include/stumpless/severity.h` and `src/severity.c`. Use what these files show to define and use a `STUMPLESS_FOREACH_TARGET_TYPE` macro to define the enumeration and a `stumpless_get_target_type_string` function.

Of course, you'll also need to add tests for the new function in `test/function/target.cpp`. Once again, you can also use the tests for the string function in `test/function/severity.cpp` as an example.

**Comment by abhakta-47** [comment]
Hi, I would like to work on this.

**Comment by abhakta-47** [comment]
`stumpless_get_severity_enum` is also present in severity.c, should I also add a similar `stumpless_get_target_type_enum` ?

**Comment by goatshriek** [comment]
Sounds good, I will assign it to you so that it is marked as in work.

Please feel free to implement `stumpless_get_target_type_enum` as well if you would like! However, it is not required for this issue.
