### ISSUE TITLE
can i know more about stumpless and what are its aspirations

### ISSUE THREAD

**Issue by cskaust** [goatshriek/stumpless#249]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem this feature would solve.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here, such as links to other discussions or related bugs.

**Comment by goatshriek** [comment]
Hello cskaust, thanks for your interest in the project!

The the [readme](https://github.com/goatshriek/stumpless#readme) and [vision](https://github.com/goatshriek/stumpless/blob/latest/docs/vision.md) documents describe what Stumpless is and its aspirations, respectively. Please have a look at these, and if there are any questions that you still have please ask them here. I'll update the documents if they leave anything unanswered.
