### ISSUE TITLE
set/override procid for entry

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#251]
Stumpless currently derives the procid field of entries from the process ID it is executing in automatically. However, the field is a 128 printable ASCII field in RFC 5424, and users may want to set this id to something more meaningful to them. This task is to implement a pair of functions to set and retrieve the procid of an entry, which is used if it is set during entry formatting.

## General Approach
There are a few details left out of the following outline, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read [this](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) section of the development documentation on adding new functions. Once you understand how this process works, you'll be ready to define the new functions.

Next, browse over the implementations of the get and set functions for the `msgid` field of an entry. While these don't deal with a default behavior, their validation and error handling flow logic will be a useful starting point.

Add the declarations for your new functions into `include/stumpless/entry.h`. They should have the following signatures:

```c
STUMPLESS_PUBLIC_FUNCTION
const char *
stumpless_get_entry_procid( const struct stumpless_entry *entry );

// ...

STUMPLESS_PUBLIC_FUNCTION
struct stumpless_entry *
stumpless_set_entry_procid( struct stumpless_entry *entry, const char *procid );
```

The implementations of these functions should go into `src/entry.c`, and the tests for them in `test/function/entry.cpp`. Be sure that you take into account the following factors while you work on this:

 * the getter should return a newly allocated buffer holding the _effective_ procid, meaning if one has not been set then the pid should be used to make the string. Make sure this is mentioned in the documentation!
 * the setter should return the modified entry in the case of success, and NULL if not.
 * setting the procid to a NULL pointer should effectively restore default behavior. Note that this is different than msgid, which uses a NILVALUE in this case, as there is no default to fall back to.
 * the procid and supporting fields (such as a valid/not valid flag) should be stored in the entry struct itself, NOT as a pointer to dynamically allocated memory
 * validate supplied procids for their length and characters. `include/private/validate.h` has a number of functions you can use to do this.
 * documentation for the functions should include everything you see in other functions, including behavior, posix safety, and a `@since` tag for the next minor release.

**Comment by Harry-Ramsey** [comment]
Hello, could I also be assigned this issue? Quick clarification, is the 128 character length excluding the null terminator?

**Comment by goatshriek** [comment]
Sure!

Correct, the 128 character length refers to 128 printable ascii characters, so the maximum size of the byte buffer will be 129. You'll see similar handling logic in `include/stumpless/entry.h` in the definition of the `stumpless_entry` struct to hold the app_name and msgid fields.

**Comment by Harry-Ramsey** [comment]
Hello, how do I retrieve the process ID using stumpless? It seems to be the only thing I can trace back to the error I am having where tests randomly segfault.

**Comment by goatshriek** [comment]
`strbuilder_append_procid` is responsible for this currently. Look in `src/formatter.c` for the usage of it.
