### ISSUE TITLE
create wide string set entry message functions

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#272]
Windows applications that support unicode characters typically use wide UTF-16 strings to represent them, instead of the UTF-8 multibyte characters that stumpless supports by default. Wide string versions of some stumpless functions are available to allow users to avoid doing conversions themselves, but not all string-based functions support this. Your task is to add a wide string version of the entry set message function using a single string.

## General Approach
There are a few details left out of the following outline, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read [this](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) section of the development documentation on adding new functions. Once you understand how this process works, you'll be ready to define the new function.

Next, review the implementation of `stumpless_set_entry_message_str` in `src/entry.c`. You'll be using these as a template for your own implementation.

The last thing to review before you start your implementation is the wrapper defined in `include/private/config/wrapper/wstring.h` called `config_copy_wstring_to_cstring`, which can be used to get a copy of a wide string as a multibyte string. You'll use this to convert the supplied wide string to a multibyte string in your functions.

Once you've done this, you should be ready to implement the new function. It should have the following signature, declared in `include/stumpless/entry.h`

```c
STUMPLESS_PUBLIC_FUNCTION
struct stumpless_entry *
stumpless_set_entry_message_str_w( struct stumpless_entry *entry,
                                   const wchar_t *message );
```

Put the implementation of this functions in `src/entry.c`.

Finally, make sure that you test your new function! Tests should go in the `test/function/entry.cpp` suite, and should cover scenarios with NULL strings and invalid wide strings being passed in, in addition to normal expected usage.

**Comment by maxmorenorebollar** [comment]
I'll try to solve this. It hasn't been fixed has it?

**Comment by goatshriek** [comment]
Soumds good! It has not been resolved, though #281 was an attempt that went unfinished. I recommend reading through the changes and comments there as a starting point.

**Comment by Nwogug** [comment]
Might take a crack at this as well

**Comment by goatshriek** [comment]
Hello Nwogug, you are fine to work on this if you'd like. I will leave @rodney-moreno assigned for now, as there is still one month left in the project [inactivity policy](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md#you-still-there). If you submit a pull request before then, I will reassign it earlier.

**Comment by PurpleMonkey729** [comment]
That's interesting issue. Can I try to work for it?

**Comment by goatshriek** [comment]
You are fine to work this if you would like to! Due to the other requests for this issue, I will leave it unassigned until a pull request is submitted.

**Comment by rmknan** [comment]
Hello, I am working on this. I have added the implementation and test function and other required things. Based on the build test and header checks, its passing them. I feel I am missing something are there any other tests to be run?

**Comment by rmknan** [comment]
> Finally, make sure that you test your new function! Tests should go in the test/function/entry.cpp suite, and should cover scenarios with NULL strings and invalid wide strings being passed in, in addition to normal expected usage.

I have added `Mallocfailure, Nullentry and Nullmessage Test`, are there any others that are to be added?

**Comment by goatshriek** [comment]
It sounds like you are ready to open a PR if you have all of these and they are working as expected: go ahead and open one, and I will review it when I have some time.
