### ISSUE TITLE
test wel insertion string with invalid utf-8

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#273]
The test suite for the Windows Event Log is missing tests that cover some scenarios, partially due to a lack of easy access to coverage information for Windows-enabled builds. This task is to add a test covering behavior of the library in some scenarios.

## General Approach
There are a few details left out of the following outline, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

The function you will be testing is `stumpless_set_wel_insertion_string`, which allows the specification of a string to use in place of an insertion string placeholder. The function accepts a UTF-8 (multibyte) string, which will later be converted to a UTF-16 (wide) string during usage.

Look at the existing tests for this function in `test/function/config/wel_supported.cpp`. You'll add new tests for this function in this file, where the insertion string provided is an invalid UTF-8 string. Be sure that you also test that the insertion string in the provided index is not modified when a bad string is provided, in scenarios including it is already assigned, it is out of range, and it is in range but not yet assigned.

**Comment by Boombag0607** [comment]
@goatshriek  I would like to work on this, if it is still up for the taking. Also can you provide other UTF-8 string references just for clarification?

**Comment by goatshriek** [comment]
Sure thing! The [wikipedia entry](https://en.wikipedia.org/wiki/UTF-8) is a solid place to look for a start. One of the easiest invalid states to make is an unexpected continuation byte.
