### ISSUE TITLE
element deadlock

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#274]
Multiple CI invocations have failed on the `ElementConsistency.SimultaneousReadsAndWrites` thread safety test with a deadlock. This needs to be identified and addressed.

These have happened in Windows builds, but this does not necessarily mean that the deadlock occurs in Windows-specific code.

**Comment by Harry-Ramsey** [comment]
Just wanted to look into this issue a bit if it is still occurring. Where were you looking to find the failed CI invocations?

**Comment by goatshriek** [comment]
This issue sporadically happened with CI runs on pull requests, unfortunately these have all since expired though. The test referenced above would hang until the run was cancelled.

I did find and fix one issue, but it wasn't a deadlock problem itself, so I am not confident the problem has been solved. If another run fails, I will capture the failure log and post it here.

**Comment by goatshriek** [comment]
This has not been encountered in quite a while, so I'm closing it under the assumption that the initial fix did indeed resolve it.
