### ISSUE TITLE
implement portuguese (pt-BR) localization

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#275]
There is a detailed guide on how to go about adding a new language in the [localization documentation](https://github.com/goatshriek/stumpless/blob/latest/docs/localization.md).

If you'd like a concrete example of such a change, check out commit 5529e077eb75c6e79d5634e9d7fc708828b78f89, which shows how to update the various build and header files outlined in the documentation.

**Comment by lhardt** [comment]
Working on this

**Comment by lhardt** [comment]
Hello! Can you tag it as accepted in hacktoberfest?

**Comment by goatshriek** [comment]
To my knowledge the `hacktoberfest-accepted` tag assigned to the PR is sufficient to reflect credit. It may take some time for it to show on Digital Ocean's side.
