### ISSUE TITLE
implement sinhala (si-LK) localization

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#283]
There is a detailed guide on how to go about adding a new language in the [localization documentation](https://github.com/goatshriek/stumpless/blob/latest/docs/localization.md).

If you'd like a concrete example of such a change, check out commit 5529e077eb75c6e79d5634e9d7fc708828b78f89, which shows how to update the various build and header files outlined in the documentation.

**Comment by ilallou** [comment]
Can I contribute to this ?

**Comment by goatshriek** [comment]
Of course! I will assign it to you so that others can see it is in work.

**Comment by goatshriek** [comment]
Hello @itlallou, I'm just checking in to see if this is still something you intend to do? It's no problem if you've gotten too busy elsewhere, I can simply open up the issue for others if that's the case.
