### ISSUE TITLE
set/override hostname for entry

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#294]
Stumpless currently derives the hostname field of entries from the hostname of the machine it is running on automatically. However, the field is a 255 printable ASCII field in RFC 5424, and users may want to set this to something more meaningful to them. This task is to implement a pair of functions to set and retrieve the hostnameof an entry, which is used if it is set during entry formatting.

## General Approach
There are a few details left out of the following outline, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read [this](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) section of the development documentation on adding new functions. Once you understand how this process works, you'll be ready to define the new functions.

Next, review 4b6dc9a413de51375421c9902e52021ed0d58ceb which implemented this same functionality for the procid field of entries. This commit can serve as a template for the work you need to do here.

Add the declarations for your new functions into `include/stumpless/entry.h`. They should have the following signatures:

```c
STUMPLESS_PUBLIC_FUNCTION
const char *
stumpless_get_entry_hostname( const struct stumpless_entry *entry );

// ...

STUMPLESS_PUBLIC_FUNCTION
struct stumpless_entry *
stumpless_set_entry_hostname( struct stumpless_entry *entry, const char *hostname );
```

The implementations of these functions should go into `src/entry.c`, and the tests for them in `test/function/entry.cpp`. Be sure that you take into account the following factors while you work on this:

 * the getter should return a newly allocated buffer holding the _effective_ hostname, meaning if one has not been set then the machine hostname should be used to make the string. Make sure this is mentioned in the documentation!
 * the setter should return the modified entry in the case of success, and NULL if not.
 * setting the hostname to a NULL pointer should effectively restore default behavior.
 * the hostname and supporting fields (such as a valid/not valid flag) should be stored in the entry struct itself, NOT as a pointer to dynamically allocated memory
 * validate supplied hostnames for their length and characters. `include/private/validate.h` has a number of functions you can use to do this.
 * documentation for the functions should include everything you see in other functions, including behavior, posix safety, and a `@since` tag for the next minor release.

**Comment by Gustrb** [comment]
I'm interested in tackling this issue. Is there any guid for beginners to contribute to the project? :)

**Comment by Gustrb** [comment]
I'll look into implementing this functions! Thanks for such descriptive issue, it will be really helpful
