### ISSUE TITLE
implement albanian (sq-AL) localization

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#324]
There is a detailed guide on how to go about adding a new language in the [localization documentation](https://github.com/goatshriek/stumpless/blob/latest/docs/localization.md).

If you'd like a concrete example of such a change, check out commit 5529e077eb75c6e79d5634e9d7fc708828b78f89, which shows how to update the various build and header files outlined in the documentation.

**Comment by heavylemon1** [comment]
Hello @goatshriek! :wave:
New to the project here, while looking at the localization discussion, I noticed that 
someone mentioned adding localization for Albanian.
Since I speak Albanian, I would also like to contribute if there's room for contributing on this part.
If not, that's completely understandable from my side.

Thanks!

**Comment by goatshriek** [comment]
Absolutely, the contribution would be welcome!

I do recommend that you wait a few days before beginning though - I'm very close to finishing SQLite support, which includes a number of new localized strings. It would be ideal for you to add translations after that, so that the new localization is not immediately missing strings after the addition. I'll update this issue once I have that merged into the default branch, if that's okay with you.

**Comment by heavylemon1** [comment]
Thanks @goatshriek !
Makes sense, completely understandable from my side.
I'll be watching this and the moment that the SQLite support is ready, I will start adding the localization's.
In the meantime I noticed that someone did mention that they wanted to assist on AL localization.
I want to work on this and if someone also wants to collaborate with me on this, they are welcomed on my side :smiley:

**Comment by goatshriek** [comment]
SQLite support has been merged in via #393, so you're good to go on this! I look forward to seeing your contribution!

**Comment by heavylemon1** [comment]
Great @goatshriek, will be starting working on this from tomorrow (Monday).
Thanks for letting me know!

**Comment by heavylemon1** [comment]
Hey @goatshriek !
Just wanted to let you know that I just opened PR #395 where I added the localization for Albanian.
Thanks!
