### ISSUE TITLE
expand severity from string

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#359]
The Stumpless [Rust crate and CLI tool](https://github.com/goatshriek/stumpless-logger) creates targets and entries to do whatever logging needed. In order to provide CLI support, many of these tasks need to use the strings provided in the command to set up stumpless structures. One of these is the prival used for the severity and facility values of the logged entry. To support this, the existing `stumpless_get_severity_enum` function needs to be enhanced to support the same strings that [standard logging tools](https://man7.org/linux/man-pages/man1/logger.1.html) do.

Currently the severity enum from string function only supports strings that exactly match the name of the symbol for a severity level, such as "STUMPLESS_SEVERITY_INFO". It needs to be updated to support the following strings, as well as not being case sensitive.

```
emerg
alert
crit
err
warning
notice
info
debug
panic
error
warn
```

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, review the existing implementation of `stumpless_get_severity_enum` in `src/severity.c`. Once you understand how the current implementation works, start adding the new functionality. Note that the list of new strings to accept mostly matches the end of the current symbol names without the `STUMPLESS_SEVERITY_` prefix - you can likely use this fact to simplify your implementation.

Add tests for your new functionality in the existing test module `test/function/severity.cpp`, as separate test cases from the existing ones for this function. Be sure that you test for upper and lower case versions of the strings (both should be accepted), invalid strings, empty strings, and NULL strings at a minimum.

EDIT: this issue was originally duplicative of #237 and has been updated to specify the next phase of intended functionality.

**Comment by jagw-mobica** [comment]
Can you assign me to this issue?

**Comment by jagw-mobica** [comment]
Additional question about messages ["panic", "error", "warn"] as they are deprecated, do we need to add it?
How do you want me to push the commit, as a separate PR or add it to PR https://github.com/goatshriek/stumpless/pull/380 ?

**Comment by jagw-mobica** [comment]
I can see it's not possible to create another PR so I added commit to PR #380 
It's better to merge both of them as a whole.

**Comment by goatshriek** [comment]
Yes, the deprecated terms should still work, as you have done.

A second PR would have been cleaner, but either is fine. However, I'm concerned that something is misconfigured if you say it's not possible to create another PR; what problem did you encounter?

**Comment by jagw-mobica** [comment]
Everything is fine, but I have created branch '359-severity' on top of the branch '358-facility' (because it uses the same functions the same modifications) and after pushing it to github I was able to create PR only to branch 'latest' and I wasn't able to create PR to branch '358-facility' what was my aim.
The branch '359-severity' depends on branch '358-facility' so I created additional commit '359-severity' inside the branch '358-facility' instead of creating PR.

**Comment by goatshriek** [comment]
Ah I see, yes you'll only be able to open a PR to the default branch in the main repository. I didn't think about the shared code, which certainly would have complicated things.
