### ISSUE TITLE
add benchmark for stumpless_param_to_string

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#362]
As the param to string functionality is adjusted to more closely match the formats of RFC 5424 and existing CLI tools (see #361), there is an opportunity to re-use the underlying functionality in the formatting of messages as well. This will make the performance of this function critical, as it will be used for every message formatting call where structured data including a param is present. Adding a benchmark test for `stumpless_param_to_string` will give future changes a way to evaluate what the impact to performance is.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read the [documentation](https://github.com/goatshriek/stumpless/blob/latest/docs/benchmark.md) on benchmarking in stumpless. This doc walks through the general philosophy behind benchmark tests and how they are used in this project.

Once you understand these concepts, you'll be ready to add a new benchmark in `test/performance/param.cpp` for `stumpless_param_to_string`. Make sure that your new benchmark is included in the results of the `bench` build target and when the param benchmark is run on its own using the `run-performance-test-param` target.

**Comment by iligeoili** [comment]
Hey i would like to take on this issue if its still available.

**Comment by goatshriek** [comment]
Sounds good! I will assign it to you so that others know it is in work.

**Comment by alessandro-murtas** [comment]
Hi, since it seems nobody is working on it, could i work on it?

**Comment by goatshriek** [comment]
Sure! Feel free to open a pull request as soon as you have something ready. I have not seen anything from @iligeoili to indicate that they have made progress on it.
