### ISSUE TITLE
update stumpless_element_to_string format

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#367]
The `stumpless_element_to_string` function was originally implemented with a relatively arbitrary string format similar to: `<name>:[...]` . However, as the [CLI logger](https://github.com/goatshriek/stumpless-logger) is developed, and the `stumpless_new_element_from_string` function will soone be implemented, there is a strong case for this format to instead be `name=[...]`. This change adjusts the function, it's documentation, and tests to this new format.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

There are three main things that need to change for this adjustment: the implementation itself, the documentation, and the test suite. The [development documentation](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) has everything that you need to get started and more. This change is relatively simple, so you won't need to do much more than build the library and run the test suite.

Starting with the implementation will be most straightforward approach. The function is implemented in `src/element.c`. The adjustments to match the new format should be relatively minor.

After changing the implementation, the tests will be failing. You can find them in `test/function/element.cpp`. Run the test suite (using the `check` target is the easiest way to do this). Fix anything that has broken after your update.

Finally, update the documentation in `include/stumpless/element.h` for `stumpless_element_to_string`.

You may find #366 interesting to review, as it implemented a very similar change for the param to string format.

**Comment by rmknan** [comment]
Can you assign this issue to me? I had finished it earlier. I can commit this along side the #293 and maybe you can merge both together?

**Comment by goatshriek** [comment]
That sounds fine! Please open a new pull request for this change though. This work is unrelated to that in the PR you currently have opened, and having it end up in a separate commit will ease future tasks that might arise like merge conflicts or reverting changes.
