### ISSUE TITLE
 add benchmark for stumpless_param_from_string

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#374]
As the [CLI tool](https://github.com/goatshriek/stumpless-logger) is update to use new functionality, the performance of some functions will be important to keeping the CLI fast as well. The new `stumpless_param_from_string` function is one such function, as it will be used to interpret command-line structured data arguments. Adding a benchmark test for `stumpless_param_from_string` will give future changes a way to evaluate what the impact to performance is.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read the [documentation](https://github.com/goatshriek/stumpless/blob/latest/docs/benchmark.md) on benchmarking in stumpless. This doc walks through the general philosophy behind benchmark tests and how they are used in this project.

Once you understand these concepts, you'll be ready to add a new benchmark in `test/performance/param.cpp` for `stumpless_param_from_string`. Make sure that your new benchmark is included in the results of the `bench` build target and when the param benchmark is run on its own using the `run-performance-test-param` target.

**Comment by kirubaspace** [comment]
I'll work on this

**Comment by kirubaspace** [comment]
I think you meant stumpless_new_param_from_string() . Can you please confirm @goatshriek ?

**Comment by goatshriek** [comment]
Ah yes, that's correct.
