### ISSUE TITLE
add severity from buffer

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#383]
While a function already exists to get a severity from a string, `stumpless_get_severity_enum`, it requires a NULL-terminated string. This complicates some other functions, in some cases requiring them to copy a portion of a string in order to NULL-terminate it. This change is to add a new function `stumpless_get_severity_enum_from_buffer` which uses a buffer and a length instead of a NULL-terminated string.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read [this](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) section of the development documentation on adding new functions. Once you understand how this process works, start defining the new function.

Review the existing implementation of `stumpless_get_severity_enum` in `src/severity.c`. Once you understand how the current implementation works, start adding the new functionality to this same `src/severity.c` file and the associated header.

Add tests for your new functionality in the existing test module `test/function/severity.cpp`, based on the tests already there.

**Comment by kirubaspace** [comment]
I'd like to work on this @goatshriek

**Comment by goatshriek** [comment]
Sure thing, I've assigned it so that others know you are working it.
