### ISSUE TITLE
add a check for release date consistency

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#422]
The current release date exists in multiple places in the repository, currently the `ChangeLog.md` and `CITATION.cff`. These need to be kept consistent so that they are the same in any commit of the long-lived branches. This can be enforced by adding a check in the Github Actions workflows that are run when a change is pushed to the repository.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

The most obvious implementation of this check is a shell script that checks the release and date fields of both files and makes sure that they are the same. Note that you do NOT need to check to see if they match the current date, only that they are the same among themselves.

You can look at the solution for #372 for inspiration, which accomplished a similar goal with standardization of documentation tags.

The static analysis CI step this check should be added to the workflows in `.github/workflows/analysis.yml`. Exactly how you implement this check is up to you, but here are a few guidelines to keep in mind:

* It needs to run in the Github Actions environment at a minimum, and ideally is something that others can run themselves without installing extra software. A bash script in the `scripts` folder would work, or even a simple `grep` command directly in the action itself.
* Include the file and line number of discovered offenses. Developers must be able to quickly identify what the check is looking for, why it is failing, and where the offense is so that it can be corrected.

**Comment by jhayden02** [comment]
Is anyone currently working on this? I think this is an achievable first issue for me with some work.

**Comment by goatshriek** [comment]
No one has claimed this one yet; if you'd like to take it on I can assign it to you so others know it is in work.

**Comment by jhayden02** [comment]
Yeah that'd be great!

**Comment by goatshriek** [comment]
Thanks very much for your work implementing this and correcting the issues quickly!
