### ISSUE TITLE
add memory function accessors

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#447]
While stumpless currently provides a way to control the functions used to manage dynamic memory, it does not provide matching functions to retrieve the current settings. This may be useful to library users, and would also make some of the testing code cleaner as well.

## General Approach
There are a few details left out of the following outline, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read [this](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) section of the development documentation on adding new functions. Once you understand how this process works, you'll be ready to define the new functions.

Add your three new functions to `include/stumpless/memory.h` and the corresponding source file. You should also add tests for your new functions in `test/function/memory.cpp`.

Finally, update the memory counting macros used in benchmark tests to use your new functions. These are defined in `include/test/helper/memory_counter.hpp`. They currently assume that the settings to restore are the standard library functions, but this may not always be the case. Change the `INIT_MEMORY_COUNTER` macro to use your new functions instead of making this assumption.

**Comment by tertyshnyi** [comment]
Hi, I'd like to do this task. Can you assign it to me?

**Comment by goatshriek** [comment]
Sure, good luck!

**Comment by tertyshnyi** [comment]
![изображение_2024-10-11_143617058](https://github.com/user-attachments/assets/07b5625c-8edf-47c4-92e5-5126af3c5905)

Can you help explain what the problem might be?

**Comment by goatshriek** [comment]
What is the problem? The screenshot seems to simply show the entry example running.

**Comment by tertyshnyi** [comment]
Thank you for answering. If that's the way it's supposed to be, then I'll get to the task at hand.

**Comment by goatshriek** [comment]
Closed by #468.
