### ISSUE TITLE
add benchmark for stumpless_open_buffer_target

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#449]
Buffer targets are use heavily in test suites, and will also be employed internally for new features. Adding a benchmark test for `stumpless_open_buffer_target` will give future changes a way to evaluate what the impact to performance is.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read the [documentation](https://github.com/goatshriek/stumpless/blob/latest/docs/benchmark.md) on benchmarking in stumpless. This doc walks through the general philosophy behind benchmark tests and how they are used in this project.

Once you understand these concepts, you'll be ready to add a new benchmark suite as `test/performance/target/buffer.cpp` for `stumpless_open_buffer_target`. Look to the existing test suites as a starting point for your new one. To add the new benchmark suite to the build process, you'll need to modify `CMakeLists.txt` with a call to `add_performance_test` for the new benchmark suite. Make sure that you are able to see results from your new test when you run the benchmark suite using the `bench` make target.

**Comment by m3g4d1v3r** [comment]
Hello there!
I've opened a pull request in order to solve this issue.
https://github.com/goatshriek/stumpless/pull/466
It's still a Work In Progress.

**Comment by goatshriek** [comment]
Resolved by #466
