### ISSUE TITLE
priority to string function

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#450]
A function exists to get the string representation of a prival, `stumpless_get_prival_string`, which returns a string version of the two enumerations used to create the prival. However, this is longer and more verbose than need be, and a more succinct representation would follow the priority string convention used by tools like [logger](https://man7.org/linux/man-pages/man1/logger.1.html), for example `local3.info`. You will write a second function that generates this shorter form string for a prival.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

First, read [this](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md#adding-new-functions) section of the development documentation on adding new functions. Once you understand how this process works, start defining the new function.

Review the existing implementation of `stumpless_get_prival_string` in `src/prival.c`. Once you understand how the current implementation works, start adding the new functionality to the same file and the associated header, in a function named `stumpless_get_priority_string`.

Note that `stumpless_prival_from_string` accepts strings in the same format of `facility.severity`. You can reference this implementation for ideas on how to implement the new function.

Add tests for your new functionality in the existing test module `test/function/prival.cpp`, based on the tests already there.

**Comment by KlowdfurrRad** [comment]
Hi, 
I would like to work on this. This would be my first contribution. My background is mostly C++ and some C.

**Comment by goatshriek** [comment]
There is already PR #457 open to resolve this issue. Are there any other issues in the repository that you are interested in? There may be some more to string function implementation issues added in the next week or so as well.

**Comment by KlowdfurrRad** [comment]
Oh okay. Can I work on param into string function in that case? 
This one seems to not be assigned. But if someone is working on it I am interested in trying entry to string as well.

**Comment by goatshriek** [comment]
Either of those should be fine! Whichever you would like can be assigned, just drop a comment on the issue you'd like (not here).

**Comment by m3g4d1v3r** [comment]
Hello @KlowdfurrRad and @goatshriek.
Can I co-author PR #457? If you don't mind, I can make some commits after the old ones in order to let the PR pass the tests.

**Comment by goatshriek** [comment]
With no response from the original author, I think you're safe to bring it across the finish line. Abandoned PRs are not uncommon, particularly around Hacktoberfest.

**Comment by goatshriek** [comment]
Resolved by #476.
