### ISSUE TITLE
Documentation: broken link on https://github.com/goatshriek/stumpless/blob/latest/docs/portability.md

### ISSUE THREAD

**Issue by vasiliyk** [goatshriek/stumpless#471]
**Describe the bug**
The link in the sentence "A complete list of the symbols in this header can be found in the [documentation](https://goatshriek.github.io/stumpless/docs/c/latest/config_8h.html)." is broken on the page https://github.com/goatshriek/stumpless/blob/latest/docs/portability.md.

**Comment by goatshriek** [comment]
Thank you very much for reporting this! I've corrected the link in the `typo-fix` branch [here](https://github.com/goatshriek/stumpless/blob/typo-fix/docs/portability.md). This branch will get merged in after Hacktoberfest concludes, along with a variety of other doc-based tweaks and fixes.

**Comment by goatshriek** [comment]
Fixed by #480.
