### ISSUE TITLE
error codes are not included in perror output

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#53]
The error id is not included in the output of `stumpless_perror`, which could add some extra steps when troubleshooting. The goal of the perror function is to prevent manual print statements, and there is also not a way to easily get the name of the error even if the code itself is retrieved (as it will be an integer and not a string).

This could easily be solved by adding a new public function like `stumpless_get_error_id_string` that spits out a string representation of an error id enum. This could then be used in the perror function to add the error id in an easily readable format.

**Comment by pedestrianlove** [comment]
Hi there, I'm planning on doing this one, could you please assign this to me?

Great thanks!

**Comment by goatshriek** [comment]
No problem - let me know if you run into any stumbling blocks or need clarification on anything.

**Comment by pedestrianlove** [comment]
@goatshriek Sorry, I don't know where to put the retrieved string from the enum stumpless_error_id.
Should I put it in the code_type in struct stumpless_error or just print it out independently in stumpless_perror function?

Thanks for your clarification!

**Comment by goatshriek** [comment]
Here's a little more detail on the way to solve this that I like the most - it certainly isn't the only way, but I think it is the simplest and best solution here.

I would start by defining a new function `stumpless_get_error_id_string` (or something else that gets the point across) in `src/error.c` (and declaring it in `include/stumpless/error.h`) that takes in an `enum stumpless_error_id` and returns a hard-coded string literal. Others would then be able to use this function if they want to build their own custom error codes or get the string for any other reason. This would basically just be a large switch statement with entries like:

```c
//...
case STUMPLESS_ELEMENT_NOT_FOUND:
  return "ELEMENT_NOT_FOUND";
//...
```

Then you would just need to modify `stumpless_perror` so that it spits out this string before the message, something like `fputs( <call_to_your_new_function>, error_stream );`. I would also tack on a colon and space after this and before the message to give it a cleaner look. You can see where the prefix is printed (lines 70-74 of `src/error.c`) to see how to do this while avoiding slower calls like `fprintf`.

After you do that, you just need to add a test statement in `test/function/error.cpp` to make sure it's there in printed errors. This could just be a single `EXPECT_THAT` statement in the existing tests making sure that the string is there with `HasSubstr` - there are already many checks in that same test suite that you could use as an example.
