### ISSUE TITLE
build fails in cygwin

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#60]
## Short description of Problem
Attempting to build stumpless in a cygwin environment with the required packages fails.

## Environment Description
This has been tested in a Windows 10 build 10240 with cygwin64 3.1.2.

## Other details
Current problems with this build appear to come primarily from conflicting type definitions between standard Unix headers (sys/socket.h, unistd.h) and the Windows headers (windows.h, winsock2.h). These are both detected by cmake, and when the library is compiled with both headers conflicting type definitions emerge. Disabling socket and network targets does not alleviate the issue.

Some other smaller problems also arise with Windows functionality and gtest, which should be easier to work around.

**Comment by goatshriek** [comment]
This was noted during work on #52 by @annesuzuki

**Comment by goatshriek** [comment]
A workaround to get (most) functionality working in cygwin is to add the following hardcoding of the header checks to `CMakeLists.txt` to avoid header conflicts directly after the `check_include_files` calls:

    if(HAVE_SYS_SOCKET_H AND HAVE_WINSOCK2_H)
      set(HAVE_WINSOCK2_H FALSE)
      set(HAVE_WINDOWS_H FALSE)
    endif(HAVE_SYS_SOCKET_H AND HAVE_WINSOCK2_H)

This will force the build environment to use the standard Unix headers.

In order to fix the Google Test builds, you will also need to adjust the `-std=c++11` flag in the `tools/cmake/test.cmake` file to instead be `-std=gnu++11`.

Note that some of the network target tests still failed (at least for me) after these updates. A new branch to support cygwin builds will be created and incorporated into version 1.5.0.

**Comment by annesuzuki** [comment]
![Screenshot1](https://user-images.githubusercontent.com/19434179/72957821-da2d3180-3d59-11ea-8b35-5d1c44068749.png)
![Screenshot2](https://user-images.githubusercontent.com/19434179/72957822-da2d3180-3d59-11ea-9d1c-70893e926dce.png)

**Comment by annesuzuki** [comment]
These are the screenshots of the errors I'm getting. Everything up until make all is ok.

**Comment by goatshriek** [comment]
Hmm, for some reason it appears your system doesn't have `unistd.h` available. Could you post the output of your `cmake` command in a fresh build directory? I used gcc in my cygwin build, but perhaps you are using mingw or something else that behaves differently.

I will make sure that the cygwin branch can builid in this situation as well.

**Comment by goatshriek** [comment]
I've created a branch named `portability` to handle the scenario in the screenshots above - please give it a try next time and see if it resolves the issues in the above screenshots. I've also added a [Travis CI test](https://travis-ci.org/goatshriek/stumpless/jobs/641169751) which failed with the same symptoms as above which [now works](https://travis-ci.org/goatshriek/stumpless/builds/641170817) on this branch.

I will add other portability-related fixes to this branch to overcome other portability-related problems identified here. I have not added the workaround for the `CMakeLists.txt` file mentioned above, as I hope to be able to work out a less blunt way to avoid conflicts.

**Comment by annesuzuki** [comment]
[std_out.txt](https://github.com/goatshriek/stumpless/files/4116127/std_out.txt)
[std_error.txt](https://github.com/goatshriek/stumpless/files/4116128/std_error.txt)
Output and standard error for the cmake, make all and make test commands.

**Comment by goatshriek** [comment]
I've made some updates that get the `portability` branch building and running the tests, although there are still some warnings in the Windows Event Log module compilation and failing tests for socket and WEL targets. Give it a shot and see if you get some better results.

Any suggestions on how to add CI testing to prevent regressions of Cygwin support are welcome. From a quick glance the best option seems to be the Travis CI MSYS2 support, but I will need to dive into this further.

Thank you for your patience while this gets resolved!

**Comment by goatshriek** [comment]
Builds on my cygwin installation now complete without any errors, including the tests (via `make check`). Please confirm if your issues are resolved as well, or post any other problems you encounter here. I'll continue cleaning up the documentation and fine-tuning some configurations in the meantime.

**Comment by goatshriek** [comment]
I've created pull request #61 to merge in the support for cygwin (and mingw along the way). I'll go ahead and merge it in a week (on 1 March) unless there are any other issues noted here.

**Comment by goatshriek** [comment]
This has been merged into master in release 1.5.0. Please report any further issues with Cygwin support in a new issue.
