### ISSUE TITLE
implement PID option

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#77]
Stumpless currently does not support the `STUMPLESS_OPTION_PID` option despite providing it in its header files. This could easily be implemented by checking the target's setting for this option during formatting, and using `NILVALUE` (a dash character) if this option is not set.

This option should be off by default, being enabled by `stumpless_set_option` on a target. This is a change in current behavior, but brings the library closer to the behavior described by [`syslog`](https://man7.org/linux/man-pages/man3/syslog.3.html), which this library currently attempts to stay in line with where possible and reasonable.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here and someone can help you get past the stumbling block. You are also free to take a different approach if you feel it is better - this is merely meant as a starting point.

First, have a look at the [documentation](https://goatshriek.github.io/stumpless/docs/c/latest/target_8h.html) for `stumpless_get_option`, `stumpless_set_option`, and `stumpless_unset_option` in `include/stumpless/target.h`. You will not need to modify any of these, but you will use them in your implementation so they are important to understand.

Next, check out `stumpless_add_entry` in `src/target.c`. This is the workhorse function for logging messages, and includes the calls to format messages before sending them. The formatting call currently only uses the `stumpless_entry` struct to create the message, but this will not be enough to tell if the target's option is set.

There are a few possible solutions. You could add a completely new formatting function (something like `format_entry_without_pid`) to `src/formatter.c` that does not use the procid of the entry. You could change the current formatting function to also take a pointer to the `stumpless_target` struct that it can use to check the option while formatting. You could change the current formatting function to simply take a boolean switch on whether to use the pid or not. Or you could solve it  a different way. The specific approach is up to you - just make sure that you can explain why you feel it's the best approach. The end result should be that if `STUMPLESS_OPTION_PID` is not set on the target, then the `PROCID` field of the logged message is a single dash character, the RFC 5424 NILVALUE.

Once this is done, add some tests to make sure that the behavior is as intended. Test code already exists to make sure that setting and unsetting the option behaves as expected - look for `TEST( SetOption, Pid )` in `test/function/target.cpp`. Use this test as a starting point to create a new test that logs a message before and after setting the option. The message logged before the option is set should not include the pid. The message logged after should have it. To detect whether the pid section is a dash or a value will require some work - you could write your own regex, or check out the [Google Mock matchers](https://github.com/google/googletest/blob/master/googlemock/docs/cheat_sheet.md) to perhaps make this easier. For details on the format of the messages, you can refer to the [RFC](https://tools.ietf.org/html/rfc5424#section-6) that stumpless follows (don't let the RFC intimidate you, the format section is pretty easy to follow).

**Comment by TylerStanish** [comment]
Hi, I think I can try doing this

**Comment by goatshriek** [comment]
Hi Tyler, sounds good! I've assigned the issue to you so that it is marked - please reach out if you need any help/guidance or if you run into something that's broken. Others working on first issues have definitely noticed opportunities to improve the documentation, so if you feel something can be made clearer please let me know!
