### ISSUE TITLE
implement PERROR option

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#81]
Stumpless currently does not currently have any equivalent of the LOG_PERROR option provided by traditional syslog implementations. This should be implemented as another option, and made compatible with LOG_PERROR on systems that have it.

The meaning of the option is simple (it is described briefly in the [syslog manpage](https://man7.org/linux/man-pages/man3/syslog.3.html)). Targets with this option set should also write their message to `stderr` as well as the target itself.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here and someone can help you get past the stumbling block. You are also free to take a different approach if you feel it is better - this is merely meant as a starting point.

First, have a look at the documentation for `stumpless_get_option`, `stumpless_set_option`, and `stumpless_unset_option` in `include/stumpless/target.h`. You will not need to modify any of these, but you will use them in your implementation so they are important to understand.

Next, check out `stumpless_add_entry` in `src/target.c`. This is the workhorse function for logging messages, and is a good place to put the logic to handle this option. The change will be simple - before calling the `sendto` function for the target, you will check to see if the option is set, and if it is, then print the formatted message to `stderr`.

Don't forget to document the option after you implement it in `include/stumpless/option.h`.

Once you have implemented this, be sure to add a test for the functionality. Test code already exists to make sure that setting and unsetting the option behaves as expected - look for `TEST( SetOption, Pid )` in `test/function/target.cpp`. Use this test as a starting point to create a new test that logs a message before and after setting the option to make sure no runtime failures occur. It may be difficult to capture `stderr` itself for the test, and so if you cannot figure out a way to do this then it can be handled in a future change.

**Comment by Jk-bit** [comment]
I would like to work on this issue

**Comment by goatshriek** [comment]
Sounds good! I think you'll find this one more exciting than your last change.

**Comment by Jk-bit** [comment]
I have read the necessary material required, I have planned a rough idea to proceed on
   -> The message to be logged is returned by the function `strbuilder_get_buffer` defined in `src/strbuilder.c` on line 169. So before calling any `sendto_*` function we need to check the option PERROR if it set or not. If yes then we print the message on the stderr as well.
   -> I am planning to use `fprintf(stderr, buffer)` to print the error in stderr

Please correct if I am wrong in my understanding.

**Comment by goatshriek** [comment]
Yes, I believe you will be successful with that approach! Here are a few points for you to consider as you implement it:
* The message to be logged is indeed returned on line 133 of `src/target.c` from `strbuilder_get_buffer`, and would be the right thing to log to the error stream. However, some target types are logged before reaching that call and the buffer will not have been created for them. You will need to do the option check before any of these calls are made (as they directly return), and fill the buffer and write to the error stream there if needed. You can then change the code around line 133 to check and see if the buffer needs to be filled and only do so if needed (calling `format_entry` twice would be a significant performance impact).
* `fwrite` will be safer and likely more performant than `fprintf` since you already have the buffer size, use this instead
* Rather than using `stderr` directly, make a call to `stumpless_get_error_stream` from `stumpless/error.h` to get the correct error stream to use, as it may have been configured to be something else. My apologies, I forgot to mention this in the initial issue write-up, so there is no way that you would have known to do this.

Again, great work, it sounds like you have a good handle on things. I'm looking forward to seeing your pull request! Of course let me know if you have any other questions.

**Comment by Jk-bit** [comment]
I have implemented the perror option and define a function which writes into the error_stream returned by `stumpless_get_error_stream`. 
I wanted to know how to test the function implemented by me.

**Comment by goatshriek** [comment]
If you're feeling a little lost on the tests in general, `docs/test.md` is a good place to start. If there's information that you feel that doesn't cover adequately, please let me know and I'll see what I can do to fix it.

For this specific test, start by copying the function starting [here](https://github.com/goatshriek/stumpless/blob/latest/test/function/target.cpp#L705) in the same file, and altering the copy to use the PERROR option instead of the PID one. You should see the same results with and without the option set, but it's still important to test that to makes sure no unintended changes have been introduced. Then run the test suite using the procedures described in `docs/test.md` and make sure that you see your new test in the output and that it is passing.

**Comment by Jk-bit** [comment]
Pull Request #202, Please check
