### ISSUE TITLE
implement NOWAIT option

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/stumpless#82]
Stumpless currently does not support the STUMPLESS_OPTION_NOWAIT option despite providing it in its header files. This option is meant to mirror the LOG_NOWAIT option in functionality, and should be straightforward to implement as stumpless does not currently spawn any child processes during logging. If no work is actually required to implement, then this will simply amount to a documentation exercise.

Don't forget to document the option after you implement it in `include/stumpless/option.h`.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

**Comment by Jk-bit** [comment]
I would like to work on this issue, I am new to open source contribution but I have strong knowledge in C programming language. Currently I am browsing the code of the same, and trying to understand the code. I would like your thoughts on the same, so that I can quickly start to work on the issue.

**Comment by goatshriek** [comment]
Absolutely! I will assign the issue to you while you work on it.

The main starting point will be the `stumpless_add_entry` function in the `src/target.c` file, which is responsible for calling all of the logging functions. I recommend you use an IDE or ctags so that you can jump to the definitions of the functions it calls to log each type of message.

Once you've confirmed to your satisfaction that no child processes are spun off, the documentation for the option is in `include/stumpless/option.h` on line 61. You will just need to update this to reflect the meaning of the option, along with a clarification that this option is in effect always on.

**Comment by Jk-bit** [comment]
I have checked the source code and have understood that there are no child processes created, thus there is minimal implementation for this issue only if there is an idea of having child processes in future.This can be done by checking the option and if the NOWAIT option is set then we should not wait otherwise we need to wait. 
If there is no any plan to have child processes then only documentation exercise is needed. 

So, I just need a clarification whether in future version, is there any plan to have child processes?

**Comment by goatshriek** [comment]
There is no plan to create any child processes during logging calls, as this would be too slow. You can proceed under the assumption that this will always be the case.

**Comment by Jk-bit** [comment]
So in that case there is no need for implementing NOWAIT, it's just an documentation part that's need to be done on line 61 of include/stumpless/option.h

**Comment by goatshriek** [comment]
Correct, you'll just need to describe what the option means and that it is essentially always on.

**Comment by Jk-bit** [comment]
#201 pull request for documentation of NOWAIT
